import 'dotenv/config';
import express from 'express';
import cookieParser from 'cookie-parser';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import pg from 'pg';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const {Pool}=pg;
const app=express();
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
const JWT_SECRET=process.env.JWT_SECRET;if(!JWT_SECRET)throw new Error('JWT_SECRET is required');
app.use(express.json({limit:'10mb'}));app.use(cookieParser());app.use(express.static(path.join(__dirname,'public')));

function sign(u){return jwt.sign({sub:u.id},JWT_SECRET,{expiresIn:'30d'})}
function setAuth(res,u){res.cookie('bpn_session',sign(u),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:30*24*60*60*1000,path:'/'})}
function clearAuth(res){res.clearCookie('bpn_session',{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',path:'/'})}
function publicUser(u){return {id:u.id,student_code:u.student_code,email:u.email,name:u.name,username:u.username,avatar_url:u.avatar_url,role:u.role,status:u.status,target_exam:u.target_exam,exam_date:u.exam_date,daily_target:u.daily_target,xp:u.xp,level:u.level,streak_days:u.streak_days,last_activity_date:u.last_activity_date,last_login_at:u.last_login_at,preferences:u.preferences,created_at:u.created_at}}
async function auth(req,res,next){try{const t=req.cookies.bpn_session;if(!t)return res.status(401).json({error:'Authentication required'});const d=jwt.verify(t,JWT_SECRET);const q=await pool.query('SELECT * FROM users WHERE id=$1',[d.sub]);const u=q.rows[0];if(!u)return res.status(401).json({error:'Session expired'});if(u.status!=='active')return res.status(403).json({error:'Account is '+u.status});req.user=u;next()}catch{return res.status(401).json({error:'Invalid session'})}}
function admin(req,res,next){if(req.user?.role!=='admin')return res.status(403).json({error:'Admin access required'});next()}
async function audit(actor,action,target,details={}){try{await pool.query('INSERT INTO audit_logs(actor_user_id,action,target_user_id,details) VALUES($1,$2,$3,$4)',[actor?.id||null,action,target||null,details])}catch(e){console.error('audit',e.message)}}
function makeStudentCode(){return 'BPN-'+new Date().getFullYear().toString().slice(-2)+'-'+crypto.randomBytes(3).toString('hex').toUpperCase()}
function makePassword(){return crypto.randomBytes(5).toString('base64url')+'@1'}
async function bootstrapAdmin(){if(!process.env.ADMIN_EMAIL||!process.env.ADMIN_PASSWORD)return;const email=process.env.ADMIN_EMAIL.trim().toLowerCase();const found=await pool.query('SELECT id FROM users WHERE email=$1',[email]);if(found.rows[0]){await pool.query("UPDATE users SET role='admin',status='active' WHERE email=$1",[email]);return}const hash=await bcrypt.hash(process.env.ADMIN_PASSWORD,12);await pool.query("INSERT INTO users(student_code,email,password_hash,name,username,role,status) VALUES($1,$2,$3,$4,$5,'admin','active')",[makeStudentCode(),email,hash,process.env.ADMIN_NAME||'BPSC Nexus Admin',process.env.ADMIN_USERNAME||'admin']);console.log('Initial admin created:',email)}

app.get('/api/health',async(_req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,database:true})}catch(e){res.status(503).json({ok:false,database:false,error:e.message})}});

app.post('/api/auth/register',async(req,res)=>{const {email,password,name,username}=req.body||{};if(!email||!password||!name)return res.status(400).json({error:'Name, email and password are required'});if(password.length<8)return res.status(400).json({error:'Password must be at least 8 characters'});try{const hash=await bcrypt.hash(password,12);const code=makeStudentCode();const q=await pool.query(`INSERT INTO users(student_code,email,password_hash,name,username) VALUES($1,$2,$3,$4,$5) RETURNING *`,[code,email.trim().toLowerCase(),hash,name.trim(),username?.trim()||null]);setAuth(res,q.rows[0]);res.status(201).json({user:publicUser(q.rows[0])})}catch(e){res.status(409).json({error:e.code==='23505'?'Email, username or student ID already exists':'Could not create account'})}});
app.post('/api/auth/login',async(req,res)=>{const {identifier,password}=req.body||{};const login=(identifier||req.body?.email||'').trim();if(!login||!password)return res.status(400).json({error:'User ID/email/username and password are required'});const q=await pool.query(`SELECT * FROM users WHERE lower(coalesce(email,''))=lower($1) OR lower(coalesce(username,''))=lower($1) OR lower(coalesce(student_code,''))=lower($1) LIMIT 1`,[login]);const u=q.rows[0];if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'Invalid credentials'});if(u.status!=='active')return res.status(403).json({error:'Account is '+u.status});await pool.query('UPDATE users SET last_login_at=NOW(),updated_at=NOW() WHERE id=$1',[u.id]);setAuth(res,u);res.json({user:publicUser({...u,last_login_at:new Date().toISOString()})})});
app.post('/api/auth/logout',(req,res)=>{clearAuth(res);res.json({ok:true})});
app.get('/api/auth/me',auth,(req,res)=>res.json({user:publicUser(req.user)}));
app.patch('/api/profile',auth,async(req,res)=>{const allowed=['name','username','avatar_url','target_exam','exam_date','daily_target','preferences'];const data=Object.fromEntries(Object.entries(req.body||{}).filter(([k])=>allowed.includes(k)));const keys=Object.keys(data);if(!keys.length)return res.json({user:publicUser(req.user)});const sets=[],vals=[];keys.forEach((k,i)=>{sets.push(`${k}=$${i+1}`);vals.push(data[k])});vals.push(req.user.id);try{const q=await pool.query(`UPDATE users SET ${sets.join(',')},updated_at=NOW() WHERE id=$${vals.length} RETURNING *`,vals);res.json({user:publicUser(q.rows[0])})}catch(e){res.status(409).json({error:e.code==='23505'?'Username already exists':'Profile update failed'})}});

// Planner
app.get('/api/planner',auth,async(req,res)=>{const date=req.query.date;const p=[req.user.id];let s='SELECT * FROM planner_tasks WHERE user_id=$1';if(date){p.push(date);s+=' AND task_date=$2'}s+=' ORDER BY task_date,priority DESC,created_at';res.json({tasks:(await pool.query(s,p)).rows})});
app.post('/api/planner',auth,async(req,res)=>{const {task_date,title,subject,target,priority}=req.body||{};if(!task_date||!title)return res.status(400).json({error:'Date and title are required'});const q=await pool.query(`INSERT INTO planner_tasks(user_id,task_date,title,subject,target,priority) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[req.user.id,task_date,title,subject||null,target??null,priority||'normal']);res.status(201).json({task:q.rows[0]})});
app.patch('/api/planner/:id',auth,async(req,res)=>{const {completed,title,subject,target,priority,task_date}=req.body||{};const q=await pool.query(`UPDATE planner_tasks SET completed=COALESCE($1,completed),title=COALESCE($2,title),subject=COALESCE($3,subject),target=COALESCE($4,target),priority=COALESCE($5,priority),task_date=COALESCE($6,task_date),completed_at=CASE WHEN COALESCE($1,completed)=TRUE THEN COALESCE(completed_at,NOW()) ELSE NULL END,updated_at=NOW() WHERE id=$7 AND user_id=$8 RETURNING *`,[completed??null,title??null,subject??null,target??null,priority??null,task_date??null,req.params.id,req.user.id]);if(!q.rows[0])return res.status(404).json({error:'Task not found'});res.json({task:q.rows[0]})});
app.delete('/api/planner/:id',auth,async(req,res)=>{const r=await pool.query('DELETE FROM planner_tasks WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);res.json({deleted:r.rowCount===1})});

// Test library + engine
app.get('/api/tests',auth,async(req,res)=>{const p=[];let s='SELECT * FROM tests WHERE published=TRUE';if(req.query.institution){p.push(req.query.institution);s+=' AND lower(institution)=lower($1)'}s+=' ORDER BY COALESCE(year,0) DESC,COALESCE(sequence_no,999999) ASC,title';res.json({tests:(await pool.query(s,p)).rows})});
app.get('/api/tests/:id/questions',auth,async(req,res)=>{const q=await pool.query(`SELECT q.*,t.title test_title,t.duration_seconds FROM test_questions tq JOIN questions q ON q.id=tq.question_id JOIN tests t ON t.id=tq.test_id WHERE tq.test_id=$1 AND t.published=TRUE ORDER BY tq.sort_order`,[req.params.id]);res.json({test:q.rows[0]?{id:req.params.id,title:q.rows[0].test_title,duration_seconds:q.rows[0].duration_seconds}:null,questions:q.rows})});
app.post('/api/attempts',auth,async(req,res)=>{const x=req.body||{};const total=Number(x.total_questions||0),correct=Number(x.correct||0),incorrect=Number(x.incorrect||0),unattempted=Number(x.unattempted??Math.max(0,total-correct-incorrect));const accuracy=total?Number(((correct/total)*100).toFixed(2)):0;const client=await pool.connect();try{await client.query('BEGIN');const q=await client.query(`INSERT INTO test_attempts(user_id,test_id,mode,score,total_questions,correct,incorrect,unattempted,accuracy,time_taken_seconds,started_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[req.user.id,x.test_id||'unknown',x.mode==='exam'?'exam':'practice',Number(x.score||0),total,correct,incorrect,unattempted,accuracy,Number(x.time_taken_seconds||0),x.started_at||null]);const attempt=q.rows[0];for(const qa of (Array.isArray(x.question_attempts)?x.question_attempts:[])){await client.query(`INSERT INTO question_attempts(user_id,attempt_id,question_id,selected_option,correct_option,is_correct,is_bookmarked,marked_for_review,time_spent_seconds) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[req.user.id,attempt.id,qa.question_id,qa.selected_option??null,qa.correct_option??null,!!qa.is_correct,!!qa.is_bookmarked,!!qa.marked_for_review,Number(qa.time_spent_seconds||0)]);if(qa.is_correct===false&&qa.question_id){await client.query(`INSERT INTO revision_items(user_id,question_id,source,reason,next_revision_date) VALUES($1,$2,$3,$4,CURRENT_DATE+1) ON CONFLICT(user_id,question_id) DO UPDATE SET reason='answered incorrectly',next_revision_date=CURRENT_DATE+1,updated_at=NOW()`,[req.user.id,qa.question_id,x.test_id||'test','answered incorrectly'])}}
const xp=Math.min(50,Math.max(10,Math.round(correct*2)));await client.query('INSERT INTO xp_ledger(user_id,action,source_id,xp_amount) VALUES($1,$2,$3,$4)',[req.user.id,'test_completed',attempt.id,xp]);const u=await client.query('UPDATE users SET xp=xp+$1,level=FLOOR((xp+$1)/500)+1,last_activity_date=CURRENT_DATE,streak_days=CASE WHEN last_activity_date=CURRENT_DATE-1 THEN streak_days+1 WHEN last_activity_date=CURRENT_DATE THEN streak_days ELSE 1 END,updated_at=NOW() WHERE id=$2 RETURNING xp,level,streak_days',[xp,req.user.id]);await client.query("UPDATE quiz_sessions SET status='completed',updated_at=NOW() WHERE user_id=$1 AND status='in_progress' AND test_id=$2",[req.user.id,String(x.test_id||'')]);await client.query('COMMIT');res.status(201).json({attempt,awarded_xp:xp,student:u.rows[0]})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});
app.get('/api/attempts',auth,async(req,res)=>{res.json({attempts:(await pool.query('SELECT * FROM test_attempts WHERE user_id=$1 ORDER BY submitted_at DESC LIMIT 100',[req.user.id])).rows})});
app.get('/api/performance',auth,async(req,res)=>{const a=(await pool.query('SELECT * FROM test_attempts WHERE user_id=$1 ORDER BY submitted_at DESC LIMIT 100',[req.user.id])).rows;const qa=(await pool.query(`SELECT q.subject,COUNT(*) total,SUM(CASE WHEN qa.is_correct THEN 1 ELSE 0 END) correct,AVG(qa.time_spent_seconds) avg_time FROM question_attempts qa LEFT JOIN questions q ON q.id=qa.question_id WHERE qa.user_id=$1 GROUP BY q.subject ORDER BY total DESC`,[req.user.id])).rows;res.json({attempts:a,subjects:qa})});
app.get('/api/revision',auth,async(req,res)=>{const q=await pool.query(`SELECT r.*,q.question_en,q.question_hi,q.subject,q.topic,q.options,q.answer,q.explanation_en,q.explanation_hi FROM revision_items r LEFT JOIN questions q ON q.id=r.question_id WHERE r.user_id=$1 ORDER BY r.next_revision_date NULLS LAST,r.updated_at DESC`,[req.user.id]);res.json({items:q.rows})});
app.get('/api/xp',auth,async(req,res)=>{res.json({xp:req.user.xp,level:req.user.level,ledger:(await pool.query('SELECT * FROM xp_ledger WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100',[req.user.id])).rows})});
app.get('/api/leaderboard',auth,async(req,res)=>{res.json({leaders:(await pool.query(`SELECT id,student_code,name,username,xp,level,streak_days FROM users WHERE role='student' AND status='active' ORDER BY xp DESC,level DESC,created_at ASC LIMIT 100`)).rows})});

// Persistent in-progress quiz sessions
app.get('/api/quiz-sessions/current',auth,async(req,res)=>{
  const q=await pool.query("SELECT * FROM quiz_sessions WHERE user_id=$1 AND status='in_progress' ORDER BY updated_at DESC LIMIT 1",[req.user.id]);
  res.json({session:q.rows[0]||null});
});
app.post('/api/quiz-sessions',auth,async(req,res)=>{
  const b=req.body||{}; if(!b.test_id||!b.mode||!b.state)return res.status(400).json({error:'test_id, mode and state are required'});
  const mode=b.mode==='exam'?'exam':'practice';
  const client=await pool.connect();
  try{await client.query('BEGIN');
    await client.query("UPDATE quiz_sessions SET status='abandoned',updated_at=NOW() WHERE user_id=$1 AND status='in_progress'",[req.user.id]);
    const q=await client.query(`INSERT INTO quiz_sessions(user_id,test_id,mode,state,started_at,last_saved_at,updated_at) VALUES($1,$2,$3,$4,$5,NOW(),NOW()) RETURNING *`,[req.user.id,String(b.test_id),mode,b.state,b.started_at||new Date().toISOString()]);
    await client.query('COMMIT'); res.status(201).json({session:q.rows[0]});
  }catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}
});
app.patch('/api/quiz-sessions/current',auth,async(req,res)=>{
  const b=req.body||{}; if(!b.state)return res.status(400).json({error:'state is required'});
  const q=await pool.query("UPDATE quiz_sessions SET state=$1,last_saved_at=NOW(),updated_at=NOW() WHERE user_id=$2 AND status='in_progress' RETURNING *",[b.state,req.user.id]);
  if(!q.rows[0])return res.status(404).json({error:'No active quiz session'}); res.json({session:q.rows[0]});
});
app.delete('/api/quiz-sessions/current',auth,async(req,res)=>{await pool.query("UPDATE quiz_sessions SET status='abandoned',updated_at=NOW() WHERE user_id=$1 AND status='in_progress'",[req.user.id]);res.json({ok:true})});

// Admin
app.get('/api/admin/stats',auth,admin,async(_req,res)=>{const q=await pool.query(`SELECT (SELECT COUNT(*) FROM users WHERE role='student') users,(SELECT COUNT(*) FROM users WHERE role='student' AND status='active') active_users,(SELECT COUNT(*) FROM users WHERE role='student' AND status='blocked') blocked_users,(SELECT COUNT(*) FROM users WHERE role='student' AND status='deactivated') deactivated_users,(SELECT COUNT(*) FROM tests) tests,(SELECT COUNT(*) FROM questions) questions,(SELECT COUNT(*) FROM test_attempts) attempts,(SELECT COALESCE(SUM(xp_amount),0) FROM xp_ledger) xp_awarded,(SELECT COUNT(*) FROM planner_tasks WHERE completed=FALSE) open_tasks`);res.json({stats:q.rows[0]})});
app.get('/api/admin/users',auth,admin,async(req,res)=>{const search=(req.query.search||'').trim();const status=req.query.status;const p=[];let s='SELECT id,student_code,email,name,username,role,status,target_exam,xp,level,streak_days,last_login_at,created_at FROM users WHERE 1=1';if(search){p.push('%'+search.toLowerCase()+'%');s+=` AND (lower(coalesce(name,'')) LIKE $${p.length} OR lower(coalesce(email,'')) LIKE $${p.length} OR lower(coalesce(username,'')) LIKE $${p.length} OR lower(coalesce(student_code,'')) LIKE $${p.length})`}if(status){p.push(status);s+=` AND status=$${p.length}`}s+=' ORDER BY created_at DESC LIMIT 500';res.json({users:(await pool.query(s,p)).rows})});
app.post('/api/admin/users',auth,admin,async(req,res)=>{const b=req.body||{};const name=(b.name||'New Student').trim();const email=b.email?.trim().toLowerCase()||null;const username=b.username?.trim()||null;const password=b.password?.trim()||makePassword();const code=b.student_code?.trim()||makeStudentCode();if(password.length<8)return res.status(400).json({error:'Password must be at least 8 characters'});try{const hash=await bcrypt.hash(password,12);const q=await pool.query(`INSERT INTO users(student_code,email,password_hash,name,username,target_exam,daily_target,role,status) VALUES($1,$2,$3,$4,$5,$6,$7,'student','active') RETURNING *`,[code,email,hash,name,username,b.target_exam||'BPSC Prelims',Number(b.daily_target||100)]);await audit(req.user,'create_student',q.rows[0].id,{student_code:code});res.status(201).json({user:publicUser(q.rows[0]),credentials:{student_code:code,username:username||null,email,password}})}catch(e){res.status(409).json({error:e.code==='23505'?'Student ID, email or username already exists':'Could not create student'})}});
app.patch('/api/admin/users/:id/status',auth,admin,async(req,res)=>{const status=req.body?.status;if(!['active','blocked','deactivated'].includes(status))return res.status(400).json({error:'Invalid status'});if(req.params.id===req.user.id&&status!=='active')return res.status(400).json({error:'You cannot disable your own admin account'});const q=await pool.query("UPDATE users SET status=$1,updated_at=NOW() WHERE id=$2 AND role='student' RETURNING id,student_code,name,status",[status,req.params.id]);if(!q.rows[0])return res.status(404).json({error:'Student not found'});await audit(req.user,'change_user_status',req.params.id,{status});res.json({user:q.rows[0]})});
app.post('/api/admin/users/:id/reset-password',auth,admin,async(req,res)=>{const password=req.body?.password?.trim()||makePassword();if(password.length<8)return res.status(400).json({error:'Password must be at least 8 characters'});const hash=await bcrypt.hash(password,12);const q=await pool.query("UPDATE users SET password_hash=$1,updated_at=NOW() WHERE id=$2 AND role='student' RETURNING id,student_code,name",[hash,req.params.id]);if(!q.rows[0])return res.status(404).json({error:'Student not found'});await audit(req.user,'reset_password',req.params.id,{});res.json({user:q.rows[0],temporary_password:password})});
app.get('/api/admin/attempts',auth,admin,async(req,res)=>{const q=await pool.query(`SELECT a.*,u.student_code,u.name,u.email FROM test_attempts a JOIN users u ON u.id=a.user_id ORDER BY a.submitted_at DESC LIMIT 500`);res.json({attempts:q.rows})});
app.get('/api/admin/audit',auth,admin,async(req,res)=>{const q=await pool.query(`SELECT a.*,au.name actor_name,tu.name target_name FROM audit_logs a LEFT JOIN users au ON au.id=a.actor_user_id LEFT JOIN users tu ON tu.id=a.target_user_id ORDER BY a.created_at DESC LIMIT 500`);res.json({logs:q.rows})});
app.get('/api/admin/planner',auth,admin,async(_req,res)=>{const q=await pool.query(`SELECT p.*,u.student_code,u.name FROM planner_tasks p JOIN users u ON u.id=p.user_id ORDER BY p.task_date DESC,p.created_at DESC LIMIT 500`);res.json({tasks:q.rows})});
app.post('/api/admin/tests',auth,admin,async(req,res)=>{const b=req.body||{};if(!b.slug||!b.title)return res.status(400).json({error:'slug and title are required'});try{const q=await pool.query(`INSERT INTO tests(slug,title,institution,category,year,sequence_no,access_type,duration_seconds,published,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[b.slug,b.title,b.institution||null,b.category||null,b.year||null,b.sequence_no||null,b.access_type||'premium',Number(b.duration_seconds||7200),b.published!==false,b.metadata||{}]);await audit(req.user,'create_test',null,{test_id:q.rows[0].id,title:b.title});res.status(201).json({test:q.rows[0]})}catch(e){res.status(409).json({error:'Could not create test: '+e.message})}});
app.post('/api/admin/import',auth,admin,async(req,res)=>{const data=req.body||{};if(!Array.isArray(data.questions)&&!Array.isArray(data.tests))return res.status(400).json({error:'Send tests/questions/testQuestions arrays'});const client=await pool.connect();let qc=0,tc=0,tqc=0;try{await client.query('BEGIN');for(const t of data.tests||[]){await client.query(`INSERT INTO tests(id,slug,title,institution,category,year,sequence_no,access_type,duration_seconds,published,question_count,metadata) VALUES(COALESCE($1::uuid,gen_random_uuid()),$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(slug) DO UPDATE SET title=EXCLUDED.title,institution=EXCLUDED.institution,category=EXCLUDED.category,year=EXCLUDED.year,sequence_no=EXCLUDED.sequence_no,duration_seconds=EXCLUDED.duration_seconds,published=EXCLUDED.published,metadata=EXCLUDED.metadata,updated_at=NOW()`,[t.id||null,t.slug,t.title,t.institution||null,t.category||null,t.year||null,t.sequence_no||null,t.access_type||'premium',Number(t.duration_seconds||7200),t.published!==false,Number(t.question_count||0),t.metadata||{}]);tc++}for(const q of data.questions||[]){await client.query(`INSERT INTO questions(id,subject,topic,subtopic,year,language,question_en,question_hi,options,answer,explanation_en,explanation_hi,difficulty,source,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT(id) DO UPDATE SET subject=EXCLUDED.subject,topic=EXCLUDED.topic,subtopic=EXCLUDED.subtopic,year=EXCLUDED.year,language=EXCLUDED.language,question_en=EXCLUDED.question_en,question_hi=EXCLUDED.question_hi,options=EXCLUDED.options,answer=EXCLUDED.answer,explanation_en=EXCLUDED.explanation_en,explanation_hi=EXCLUDED.explanation_hi,difficulty=EXCLUDED.difficulty,source=EXCLUDED.source,metadata=EXCLUDED.metadata,updated_at=NOW()`,[q.id,q.subject||null,q.topic||null,q.subtopic||null,q.year||null,q.language||'bilingual',q.question_en||q.question||'',q.question_hi||null,q.options||[],q.answer??null,q.explanation_en||null,q.explanation_hi||null,q.difficulty||null,q.source||null,q.metadata||{}]);qc++}for(const x of data.testQuestions||[]){await client.query(`INSERT INTO test_questions(test_id,question_id,sort_order) VALUES($1,$2,$3) ON CONFLICT(test_id,question_id) DO UPDATE SET sort_order=EXCLUDED.sort_order`,[x.test_id,x.question_id,Number(x.sort_order||1)]);tqc++}await client.query(`UPDATE tests t SET question_count=(SELECT COUNT(*) FROM test_questions tq WHERE tq.test_id=t.id)`);await client.query('COMMIT');await audit(req.user,'import_content',null,{tests:tc,questions:qc,testQuestions:tqc});res.json({ok:true,tests:tc,questions:qc,testQuestions:tqc})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});

app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
const port=process.env.PORT||3000;
app.listen(port,async()=>{try{await bootstrapAdmin()}catch(e){console.error('Admin bootstrap failed:',e.message)}console.log('BPSC Nexus v2 running on :'+port)});
